routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\LibroController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\AutorController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\BibliotecaController;
use App\Http\Controllers\BinformeController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolesController;
use Spatie\Permission\Contracts\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/',[BibliotecaController::class, 'index']);

Auth::routes();

//--------------DOCENTE---------------------//

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('docente',[DocenteController::class,'index'])->name('docente.index');

// Route::get('docente/create', [DocenteController::class, 'create'])->name('docente.create');

// Route::get('docente/{docente}', [DocenteController::class, 'show'])->name('curso.show');

// Route::post('docente',[DocenteController::class,'store'])->name('docente.store');

// Route::get('docente/{docente}/edit',[DocenteController::class,'edit'])->name('docente.edit');

// Route::put('docente/{docente}',[DocenteController::class,'update'])->name('docente.update');

// Route::delete('docente/{docente}',[DocenteController::class,'destroy'])->name('docente.destroy');

Route::resource('docentes', DocenteController::class);
//--------------LIBRO---------------------//

// Route::get('libro',[LibroController::class,'index'])->name('libro.index');

// Route::get('libro/create', [LibroController::class, 'create'])->name('libro.create');

// Route::get('libro/{libro}', [LibroController::class, 'show'])->name('libro.show');

// Route::post('libro',[LibroController::class,'store'])->name('libro.store');

// Route::get('libro/{libro}/edit',[LibroController::class,'edit'])->name('libro.edit');

// Route::put('libro/{libro}',[LibroController::class,'update'])->name('libro.update');

// Route::delete('libro/{libro}',[LibroController::class,'destroy'])->name('libro.destroy');


Route::resource('libros', LibroController::class);

Route::get('biblioteca',[BibliotecaController::class, 'index']);


Route::get('/informe', [BinformeController::class, 'index']);


//--------------CATEGORIA---------------------//

// Route::get('categoria',[CategoriaController::class,'index'])->name('categoria.index');

// Route::get('categoria/create',[CategoriaController::class,'create'])->name('categoria.create');

// Route::get('categoria/{show}',[CategoriaController::class,'show'])->name('categoria.show');

// Route::post('categoria',[CategoriaController::class,'store'])->name('categoria.store');

// Route::get('categoria/{categoria}/edit',[CategoriaController::class,'edit'])->name('categoria.edit');

// Route::put('categoria/{categoria}',[CategoriaController::class,'update'])->name('categoria.update');

// Route::delete('categoria/{categoria}',[CategoriaController::class,'destroy'])->name('categoria.destroy');

Route::resource('categorias', CategoriaController::class);

//--------------AUTOR---------------------//

// Route::get('autor',[AutorController::class,'index'])->name('autor.index');

// Route::get('autor/create',[AutorController::class,'create'])->name('autor.create');

// Route::get('autor/{show}',[AutorController::class,'show'])->name('autor.show');

// Route::post('autor',[AutorController::class,'store'])->name('autor.store');

// Route::get('autor/{autor}/edit',[AutorController::class,'edit'])->name('autor.edit');

// Route::put('autor/{autor}',[AutorController::class,'update'])->name('autor.update');

// Route::delete('autor/{autor}',[AutorController::class,'destroy'])->name('autor.destroy');

Route::resource('autors', AutorController::class);

//--------------INFORME---------------------//

// Route::get('informe',[InformeController::class,'index'])->name('informe.index');

// Route::get('informe/create',[InformeController::class,'create'])->name('informe.create');

// Route::get('informe/{show}',[InformeController::class,'show'])->name('informe.show');

// Route::post('informe',[InformeController::class,'store'])->name('informe.store');

// Route::get('informe/{informe}/edit',[InformeController::class,'edit'])->name('informe.edit');

// Route::put('informe/{informe}',[InformeController::class,'update'])->name('informe.update');

// Route::delete('informe/{informe}',[InformeController::class,'destroy'])->name('informe.destroy');

Route::resource('informes', InformeController::class);
// USUARIOS Y ROLES 

Route::resource('usuarios', UsuarioController::class);
Route::resource('roles', RolesController::class);
Route::resource('perfil', PerfilController::class);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class libro extends Model
{
    use HasFactory;
    protected $fillable = ['li_image'];
}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\libro;
use Illuminate\Contracts\Cache\Store;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
// use File;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $libros = libro::all(); //::paginate(); para mostrar solo una cantidad de datos
        
        return view('libro.index', compact('libros'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('libro.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo'=> 'required',
            'autor'=> 'required',
            'descripcion'=> 'required',
            'drive' => 'required',
            'imagen' => 'required|image|max:2048',
        ]);

        //return $request->all();
        $imagenes = $request->file('imagen')->store('public/imagenes');
        
        $libro = new libro();

        $libro->li_titulo = $request->titulo;
        $libro->li_autor = $request->autor;
        $libro->li_enlace = $request->drive;
        $libro->li_image =  $url = Storage::url($imagenes);
        $libro->li_descripcion = $request->descripcion;
        
        $libro->save();

        return redirect()->route('libros.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(libro $libro)
    {
        
        return view('libro.show', compact('libro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit(libro $libro)
    {
        return view('libro.edit', compact('libro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, libro $libro)
    {
        $request->validate([
            'titulo'=> 'required',
            'autor'=> 'required',
            'descripcion'=> 'required',
            'drive' => 'required',
        ]);

        // $libro = libro::find(32);

        if($request->hasFile('imagen')){
            $request->validate([
                'imagen' =>'required|image|max:2048',
            ]);

            // $path = '/storage/imagenes/'.$request->li_image;
            // if(File::exists($path))
            // {
            //     File::delete($path);
            // }
            $url = str_replace('storage','public', $libro->li_image);
            // Storage::delete($url);

            $imagenes = $request->file('imagen')->store('public/imagenes');
            $libro->li_image = Storage::url($imagenes);

            Storage::delete($url);
        }

        //return $request->all();
        

        $libro->li_titulo = $request->titulo;
        $libro->li_autor = $request->autor;
        $libro->li_enlace = $request->drive;
        $libro->li_descripcion = $request->descripcion;
        
        $libro->save();
        
        return redirect()->route('libros.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy(libro $libro)
    {
        $url = str_replace('storage','public', $libro->li_image);
        Storage::delete($url);

        $libro->delete();

        return back()->with('eliminar', 'delete');
    }
}

resources/views/libro/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Libro')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Registrar nuevo libro</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{route('libros.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row">
            <div class="form-group col-sm-4">
            <label >Titulo</label>
            <input type="text" class="form-control" placeholder="Titulo" name="titulo" value="{{old('titulo')}}">
                @error('titulo')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Autor</label>
                <input type="text" class="form-control" placeholder="Autor" name="autor" value="{{old('autor')}}">
                @error('autor')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Enlace de drive</label>
                <input type="text" class="form-control" placeholder="drive" name="drive" value="{{old('drive')}}">
                @error('drive')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Subir Imagen</label>
                <div class="custom-file">
                <input type="file" class="custom-file-input" name="imagen" value="{{old('imagen')}}" accept="image/*" onchange="loadFile(event)">
                <label class="custom-file-label" for="inputGroupFile01">Seleccione una Imagen</label>
                </div>
                <div class="form-group">
                </div>
                @error('imagen')
                <small class="text-danger">{{$message}}</small>
                @enderror
                </div>
            </div>
            <div class="text-center">
                <img src="\storage\imagenes\default.jpg" id="output"  class="rounded img-thumbnail img-fluid" width="300" height="300">
            </div>
            <div class="form-group">
            <label for="exampleFormControlTextarea1">Descripción</label>
            <textarea class="form-control" rows="3" name="descripcion" value="">{{old('descripcion')}}</textarea>
                @error('descripcion')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="row justify-content-center">
                <a href="{{route('libros.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
                <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
            </div>
        </form>
    </div>
</div>
    {{-- 
    <div class="shadow p-5 mb-5 bg-white rounded">

    </div> --}}
@stop

@section('js')

<script>
    var loadFile = function(event){
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output = document.getElementById("output").width = "300"
    };
</script>

@stop

resources/views/libro/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Libro')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Editar libro</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        <form action="{{route('libros.update',$libro)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="row">
            <div class="form-group col-sm-4">
            <label >Titulo</label>
            <input type="text" class="form-control" placeholder="Titulo" name="titulo" value="{{old('titulo',$libro->li_titulo)}}">
                @error('titulo')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Autor</label>
                <input type="text" class="form-control" placeholder="Autor" name="autor" value="{{old('autor',$libro->li_autor)}}">
                @error('autor')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Enlace de drive</label>
                <input type="text" class="form-control" placeholder="drive" name="drive" value="{{old('drive',$libro->li_enlace)}}">
                @error('drive')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="form-group col-sm-4">
                <label>Subir Imagen</label>
                <div class="custom-file">
                <input type="file" class="custom-file-input" name="imagen" accept="image/*" onchange="loadFile(event)">
                <label class="custom-file-label" for="inputGroupFile01" >Seleccione una Imagen</label>
                </div>
                @error('imagen')
                <small class="text-danger">{{$message}}</small>
                @enderror

            </div>
            </div>
            <div class="text-center">
                <img src="{{$libro->li_image}}" id="output" class="rounded img-thumbnail" width="300" height="300">
            </div>
            <div class="form-group">
            <label for="exampleFormControlTextarea1">Descripción</label>
            <textarea class="form-control" rows="3" name="descripcion" value="">{{old('descripcion',$libro->li_descripcion)}}</textarea>
                @error('descripcion')
                <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <div class="row justify-content-center">
                <a href="{{route('libros.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
                <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
            </div>
        </form>
    </div>
</div>
    {{-- 
    <div class="shadow p-5 mb-5 bg-white rounded">

    </div> --}}
@stop

@section('js')

<script>
    var loadFile = function(event){
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output = document.getElementById("output").width = "300"
    };
</script>

@stop

resources/views/libro/index.blade.php
@extends('adminlte::page')

@section('title', 'Libro Digital')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Lista de libros</h1>
@stop

{{-- @section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.3.0/css/responsive.bootstrap4.min.css">
@stop --}}

@section('css')
{{-- <link rel="stylesheet" href="https://cdn.datatables.net/keytable/2.7.0/css/keyTable.bootstrap4.min.css"> --}}
@stop

@section('content')

<a href="{{route('libros.create')}}" class="btn btn-info mb-3">Crear Nuevo Libro</a>
<div class="card">
  <div class="card-body">
<div class="table-responsive">
    <table id="tlibro" class="table">
        <thead class="thead-dark">
          <tr>
            <th>Titulo</th>
            <th>Autor</th>
            <th>Imagen</th>
            <th>Descripcion</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($libros as $li)
          <tr>
            <td><a href="{{route('libros.show', $li)}}" class="text-decoration-none">{{$li->li_titulo}}</a></td>
            <td>{{$li->li_autor}}</td>
            <td><img src="{{asset($li->li_image)}}" alt="" width="50px"></td>
            <td class="text-justify" >{{$li->li_descripcion}}</td>
            <td width="140px">
              <a href="{{$li->li_enlace}}" class="btn btn-outline-dark btn-sm" target="_blank"><i class="fas fa-lg fa-file"></i></a>
              <a href="{{route('libros.edit', $li)}}" class="btn btn-outline-success btn-sm"><i class="fas fa-lg fa-edit"></i></a>
              <form action="{{route('libros.destroy', $li)}}" method="post" class="d-inline eliminar"> @csrf @method('delete')<button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-lg fa-trash"></i></button></form>
            </td>
          </tr>
          {{-- <img src="{{$li->li_image}}" alt=""> --}}
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@stop

{{-- <div class="container">
<div class="row">
@foreach ($libros->chunk(3) as $chunk)
<div class="card-group">
  @foreach ($chunk as $li)
  <div class="card m-2">
  <div class="col">
    <div class="card-body">
      <h5 class="card-title">{{$li->li_titulo}}</h5>
      <p class="card-text">{{$li->li_descripcion}}</p>
      <div class="df aling-items-start">
          <a href="{{$li->li_enlace}}" class="btn btn-outline-dark btn-sm" target="_blank"><i class="fas fa-lg fa-file"></i></a></td>
          <a href="{{route('libro.edit', $li)}}" class="btn btn-outline-success btn-sm"><i class="fas fa-lg fa-edit"></i></a></td>
          <form action="{{route('libro.destroy', $li)}}" method="post"> @csrf @method('delete') <button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-lg fa-trash"></i></button></form>
      </div>    
    </div>
  </div>
</div>
@endforeach
</div
@endforeach
</div>
</div> --}}

@section('js')
{{-- 
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script> --}}
{{-- <script src="https://cdn.datatables.net/responsive/2.3.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/responsive.bootstrap4.min.js"></script> --}}
{{-- <script src="https://cdn.datatables.net/keytable/2.7.0/js/dataTables.keyTable.min.js"></script> --}}
@if(session('eliminar') == 'delete')
<script>
 Swal.fire(
          '¡Eliminado!',
          'El registro ha sido eliminado.',
          'success'
        )
</script>
@endif
<script>
  $('.eliminar').submit(function(e){
    e.preventDefault();

    Swal.fire({
      title: '¿Estas seguro?',
      text: "No podrás revertir esto!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: '¡Si, eliminarlo!',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {

        this.submit();
      }
    })

  });
</script>
<script>
    $('#tlibro').DataTable({
      responsive: true,
      autoWidth: false,     
      "language": {
            "lengthMenu": "Mostrar "+`
            <select class="custom-select custom-select-sm form-control form-control-sm">
              <option value="10">10</option> 
              <option value="25">25</option> 
              <option value="50">50</option> 
              <option value="100">100</option> 
              <option value="-1">All</option> 
            </select>
            `+" registros por paginas",
            "zeroRecords": "Nada encontrado - lo siento",
            "info": "Mostrando la pagina _PAGE_ de _PAGES_",
            "infoEmpty": "No records available",
            "infoFiltered": "(filtrado de _MAX_ registro total)",
            "search":"Buscar: ",
            "paginate":{
              "next": "Siguiente",
              "previous": "Anterior"
            }
        }
    });
</script>
    
@stop

resources/views/libro/show.blade.php
@extends('adminlte::page')

@section('title', 'Libro ' . $libro->li_titulo)

@section('content_header')
    
@stop

<link rel="stylesheet" href="/css/style2.css">

@section('content')
    {{-- <div class="container">
    <div class="row mt-2">
    <div class="col-md-12 offset-md-12 mt-4">
        <div class="card">
        <div class="card-body">
            <div class="row  align-items-center">
            <div class="">
                <img src="{{$libro->li_image}}" class="img-fluid" width="400" height="600">
            </div>
            <div class="col-md-10">
                <h5 style="text-align: justify;">{{$libro->li_titulo}}</h5>
                <div class="row">
                <p class="fs-6">{{$libro->li_autor}} (Universidad Nacional del Altiplano - Puno, {{$libro->updated_at}})</p>
                <p class="lh-sm" style="text-align: justify;">
                    {{$libro->li_descripcion}}
                </p>
                </div>
            </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <a href="{{route('libros.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
        </div>
        </div>
    </div>
    </div>
</div> --}}
<div class="container py-5">
    <div class="card">
        <div class="card-body">
            <h1 class="text-center font-weight-bold text-uppercase">{{ $libro->li_titulo }}</h1>
            <div class="row">
                <div class="col-12 col-md-6 col-lg-6 pad">
                    <div class="asd">
                        <img src="{{$libro->li_image}}">
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-6">
                    <div class="card-description">
                        <p>{{$libro->li_descripcion}}</p>
                    </div>
                    <div class="">
                        <li>Titulo: {{$libro->li_titulo}}</li>
                        <li>Autor: {{$libro->li_autor}}</li>
                        <li>Enlce: <a href="{{$libro->li_enlace}}" >Visulizar</a></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@stop