routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\LibroController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\AutorController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\BibliotecaController;
use App\Http\Controllers\BinformeController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolesController;
use Spatie\Permission\Contracts\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/',[BibliotecaController::class, 'index']);

Auth::routes();

//--------------DOCENTE---------------------//

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('docente',[DocenteController::class,'index'])->name('docente.index');

// Route::get('docente/create', [DocenteController::class, 'create'])->name('docente.create');

// Route::get('docente/{docente}', [DocenteController::class, 'show'])->name('curso.show');

// Route::post('docente',[DocenteController::class,'store'])->name('docente.store');

// Route::get('docente/{docente}/edit',[DocenteController::class,'edit'])->name('docente.edit');

// Route::put('docente/{docente}',[DocenteController::class,'update'])->name('docente.update');

// Route::delete('docente/{docente}',[DocenteController::class,'destroy'])->name('docente.destroy');

Route::resource('docentes', DocenteController::class);
//--------------LIBRO---------------------//

// Route::get('libro',[LibroController::class,'index'])->name('libro.index');

// Route::get('libro/create', [LibroController::class, 'create'])->name('libro.create');

// Route::get('libro/{libro}', [LibroController::class, 'show'])->name('libro.show');

// Route::post('libro',[LibroController::class,'store'])->name('libro.store');

// Route::get('libro/{libro}/edit',[LibroController::class,'edit'])->name('libro.edit');

// Route::put('libro/{libro}',[LibroController::class,'update'])->name('libro.update');

// Route::delete('libro/{libro}',[LibroController::class,'destroy'])->name('libro.destroy');


Route::resource('libros', LibroController::class);

Route::get('biblioteca',[BibliotecaController::class, 'index']);


Route::get('/informe', [BinformeController::class, 'index']);


//--------------CATEGORIA---------------------//

// Route::get('categoria',[CategoriaController::class,'index'])->name('categoria.index');

// Route::get('categoria/create',[CategoriaController::class,'create'])->name('categoria.create');

// Route::get('categoria/{show}',[CategoriaController::class,'show'])->name('categoria.show');

// Route::post('categoria',[CategoriaController::class,'store'])->name('categoria.store');

// Route::get('categoria/{categoria}/edit',[CategoriaController::class,'edit'])->name('categoria.edit');

// Route::put('categoria/{categoria}',[CategoriaController::class,'update'])->name('categoria.update');

// Route::delete('categoria/{categoria}',[CategoriaController::class,'destroy'])->name('categoria.destroy');

Route::resource('categorias', CategoriaController::class);

//--------------AUTOR---------------------//

// Route::get('autor',[AutorController::class,'index'])->name('autor.index');

// Route::get('autor/create',[AutorController::class,'create'])->name('autor.create');

// Route::get('autor/{show}',[AutorController::class,'show'])->name('autor.show');

// Route::post('autor',[AutorController::class,'store'])->name('autor.store');

// Route::get('autor/{autor}/edit',[AutorController::class,'edit'])->name('autor.edit');

// Route::put('autor/{autor}',[AutorController::class,'update'])->name('autor.update');

// Route::delete('autor/{autor}',[AutorController::class,'destroy'])->name('autor.destroy');

Route::resource('autors', AutorController::class);

//--------------INFORME---------------------//

// Route::get('informe',[InformeController::class,'index'])->name('informe.index');

// Route::get('informe/create',[InformeController::class,'create'])->name('informe.create');

// Route::get('informe/{show}',[InformeController::class,'show'])->name('informe.show');

// Route::post('informe',[InformeController::class,'store'])->name('informe.store');

// Route::get('informe/{informe}/edit',[InformeController::class,'edit'])->name('informe.edit');

// Route::put('informe/{informe}',[InformeController::class,'update'])->name('informe.update');

// Route::delete('informe/{informe}',[InformeController::class,'destroy'])->name('informe.destroy');

Route::resource('informes', InformeController::class);
// USUARIOS Y ROLES 

Route::resource('usuarios', UsuarioController::class);
Route::resource('roles', RolesController::class);
Route::resource('perfil', PerfilController::class);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $usuarios = User::all();
        return view('usuario.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles=Role::all();
        return view('usuario.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name' =>'required',
            'email' =>'required|email|unique:users,email',
            'password' => 'required|same:contrasena-confirmar',
            'rol' => 'required'
        ]);

        $input= $request->all();
        $input['password'] = Hash::make($input['password']);

        $user=User::create($input);
        $user->assignRole($request->input('rol'));

        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $roles=Role::all();
        $usuario=User::find($id);
        return view('usuario.edit', compact('roles','usuario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $usuario=User::find($id);
        //dd($request);
        $usuario->name=$request->input('name');
        $usuario->email=$request->input('email');

        $usuario->save();
        DB::table('model_has_roles')->Where('model_id',$id)->delete();
        $usuario->assignRole($request->input('rol'));
        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::find($id)->delete();

        return redirect()->route('usuarios.index');
    }
}

resources/views/usuario/create.blade.php
@extends('adminlte::page')

@section('title', 'Usuario')

@section('content_header')
    <h1 class="text-center">Lista de Docentes</h1>
@stop

@section('content')
<a href="" class="btn btn-info mb-3">Regresar</a>
<div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
<div class="card">
    <div class="card-body">
        <form action="{{route('usuarios.store')}}" method="POST">
        @method('POST')
        @csrf
        <div class="form-row">
            <div class="col-md-6">
                <label for="">Nombre</label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="col-md-6">
                <label for="">Correo</label>
                <input type="text" class="form-control" name="email">
            </div>
            <div class="col-md-6">
                <label for="">Contraseña</label>
                <input type="text" class="form-control" name="password">
            </div>
            <div class="col-md-6">
                <label for="">Confirmar Contraseña</label>
                <input type="text" class="form-control" name="contrasena-confirmar">
            </div>
            <div class="form-group col-md-6">
                <label for="inputState">Rol</label>
                <select id="" class="form-control" name="rol">
                    @foreach($roles as $rol)
                        <option value="{{$rol->name}}">{{$rol->name}}</option>
                    @endforeach
                </select>
              </div>
        </div>
        <button class="btn btn-info">Enviar</button>
        </form>
    </div>
</div>
    </div>
</div>
@stop

resources/views/usuario/edit.blade.php
@extends('adminlte::page')

@section('title', 'Usuario')

@section('content_header')
    <h1 class="text-center">Lista de Docentes</h1>
@stop

@section('content')
<a href="" class="btn btn-info mb-3">Regresar</a>
<div class="card">
    <div class="card-body">
        <form action="{{route('usuarios.update',$usuario)}}" method="POST">
        @method('PUT')
        @csrf
        <div class="form-row">
            <div class="col-md-6">
                <label for="">Nombre</label>
                <input type="text" class="form-control" value="{{old('name',$usuario)}}" name="name">
            </div>
            <div class="col-md-6">
                <label for="">Correo</label>
                <input type="text" class="form-control" value="{{old('email',$usuario)}}" name="email">
            </div>
            <div class="col-md-6">
                <label for="">Contraseña</label>
                <input type="text" class="form-control" value="" name="password">
            </div>
            <div class="col-md-6">
                <label for="">Confirmar Contraseña</label>
                <input type="text" class="form-control" value="" name="contrasena-confirmar">
            </div>
            <div class="form-group col-md-6">
                <label for="inputState">Rol</label>
                <select id="" class="form-control" value="{{old('name',$usuario)}}" name="rol">
                    @foreach($roles as $rol)
                        <option value="{{$rol->id}}"  {{ $usuario->roles->first()->id == $rol->id ? 'selected' : '' }}>
                            {{$rol->name}}
                        </option>
                    @endforeach
                </select>

              </div>
        </div>
        <button class="btn btn-info">Enviar</button>
        </form>
    </div>
</div>
@stop

resources/views/usuario/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuario')

@section('content_header')
    <h1 class="text-center">Lista de Docentes</h1>
@stop

@section('content')

<a class="btn btn-info mb-3" href="{{route('usuarios.create')}}">Crear Nuevo Usuario</a>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped text-center">
                <thead class="thead-dark">
                    <tr>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Rol</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($usuarios as $usuario)
                        <tr>
                            <td>{{$usuario->name}}</td>
                            <td>{{$usuario->email}}</td>
                            <td>
                                @foreach($usuario->roles as $urol)
                                    <h5><span class="badge bg-warning"> {{$urol->name}} </span></h5>
                                @endforeach
    
                            </td>
                            <td>
                                <a href="{{route('usuarios.edit',$usuario->id)}}" class="btn btn-outline-success btn-sm"><i class="fas fa-lg fa-edit"></i></a>
                                <form action="{{route('usuarios.destroy',$usuario->id)}}" method="post" class="d-inline-block"> @csrf @method('delete') <button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-lg fa-trash"></i></button></form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@stop