routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\LibroController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\AutorController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\BibliotecaController;
use App\Http\Controllers\BinformeController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolesController;
use Spatie\Permission\Contracts\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/',[BibliotecaController::class, 'index']);

Auth::routes();

//--------------DOCENTE---------------------//

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('docente',[DocenteController::class,'index'])->name('docente.index');

// Route::get('docente/create', [DocenteController::class, 'create'])->name('docente.create');

// Route::get('docente/{docente}', [DocenteController::class, 'show'])->name('curso.show');

// Route::post('docente',[DocenteController::class,'store'])->name('docente.store');

// Route::get('docente/{docente}/edit',[DocenteController::class,'edit'])->name('docente.edit');

// Route::put('docente/{docente}',[DocenteController::class,'update'])->name('docente.update');

// Route::delete('docente/{docente}',[DocenteController::class,'destroy'])->name('docente.destroy');

Route::resource('docentes', DocenteController::class);
//--------------LIBRO---------------------//

// Route::get('libro',[LibroController::class,'index'])->name('libro.index');

// Route::get('libro/create', [LibroController::class, 'create'])->name('libro.create');

// Route::get('libro/{libro}', [LibroController::class, 'show'])->name('libro.show');

// Route::post('libro',[LibroController::class,'store'])->name('libro.store');

// Route::get('libro/{libro}/edit',[LibroController::class,'edit'])->name('libro.edit');

// Route::put('libro/{libro}',[LibroController::class,'update'])->name('libro.update');

// Route::delete('libro/{libro}',[LibroController::class,'destroy'])->name('libro.destroy');


Route::resource('libros', LibroController::class);

Route::get('biblioteca',[BibliotecaController::class, 'index']);


Route::get('/informe', [BinformeController::class, 'index']);


//--------------CATEGORIA---------------------//

// Route::get('categoria',[CategoriaController::class,'index'])->name('categoria.index');

// Route::get('categoria/create',[CategoriaController::class,'create'])->name('categoria.create');

// Route::get('categoria/{show}',[CategoriaController::class,'show'])->name('categoria.show');

// Route::post('categoria',[CategoriaController::class,'store'])->name('categoria.store');

// Route::get('categoria/{categoria}/edit',[CategoriaController::class,'edit'])->name('categoria.edit');

// Route::put('categoria/{categoria}',[CategoriaController::class,'update'])->name('categoria.update');

// Route::delete('categoria/{categoria}',[CategoriaController::class,'destroy'])->name('categoria.destroy');

Route::resource('categorias', CategoriaController::class);

//--------------AUTOR---------------------//

// Route::get('autor',[AutorController::class,'index'])->name('autor.index');

// Route::get('autor/create',[AutorController::class,'create'])->name('autor.create');

// Route::get('autor/{show}',[AutorController::class,'show'])->name('autor.show');

// Route::post('autor',[AutorController::class,'store'])->name('autor.store');

// Route::get('autor/{autor}/edit',[AutorController::class,'edit'])->name('autor.edit');

// Route::put('autor/{autor}',[AutorController::class,'update'])->name('autor.update');

// Route::delete('autor/{autor}',[AutorController::class,'destroy'])->name('autor.destroy');

Route::resource('autors', AutorController::class);

//--------------INFORME---------------------//

// Route::get('informe',[InformeController::class,'index'])->name('informe.index');

// Route::get('informe/create',[InformeController::class,'create'])->name('informe.create');

// Route::get('informe/{show}',[InformeController::class,'show'])->name('informe.show');

// Route::post('informe',[InformeController::class,'store'])->name('informe.store');

// Route::get('informe/{informe}/edit',[InformeController::class,'edit'])->name('informe.edit');

// Route::put('informe/{informe}',[InformeController::class,'update'])->name('informe.update');

// Route::delete('informe/{informe}',[InformeController::class,'destroy'])->name('informe.destroy');

Route::resource('informes', InformeController::class);
// USUARIOS Y ROLES 

Route::resource('usuarios', UsuarioController::class);
Route::resource('roles', RolesController::class);
Route::resource('perfil', PerfilController::class);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/informe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class informe extends Model
{
    use HasFactory;

    protected $fillable = ['info_pdf'];

    //protected $fillable = ['doce_id', 'cate_id', 'au_id'];
    //return $this->belongsTo(Autor::class, 'au_id', 'id');

    public function autor(){
        return $this->belongsTo(Autor::class);
    }

    public function docente(){
        return $this->belongsTo(Docente::class);
    }

    public function categoria(){
        return $this->belongsTo(Categoria::class);
    }

}

app/Http/Controllers/InformeController.php
<?php

namespace App\Http\Controllers;

use App\Models\autor;
use App\Models\docente;
use App\Models\informe;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use App\Models\categoria;
use Illuminate\Contracts\Cache\Store;
use Illuminate\Support\Facades\Storage;


class InformeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $informe = Informe::All();
        return view('informe.index', compact('informe'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $docente = Docente::all();
        $categoria = Categoria::all();
        $autor = Autor::all();
        //dd($docente);
        return view('informe.create', compact('docente','categoria','autor'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required',
            'descripcion'=>'required',
            'codigo'=>'required',
            'pdf'=>'required',
            'fecha'=>'required',
            'centro'=>'required',
            'docente'=>'required',
            'categoria'=>'required',
            'autor'=>'required',
        ]);

        $pdf = $request->file('pdf')->store('public/documento');

        $informe = new informe();

        $informe->info_nombre = $request->nombre;
        $informe->info_descripcion = $request->descripcion;
        $informe->info_codigo = $request->codigo;
        $informe->info_centro = $request->centro;
        $informe->info_pdf = $url = Storage::url($pdf);
        $informe->info_fecha = $request->fecha;
        $informe->docente_id = $request->docente;
        $informe->categoria_id = $request->categoria;
        $informe->autor_id = $request->autor;

        $informe->save();

        return redirect()->route('informes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\informe  $informe
     * @return \Illuminate\Http\Response
     */
    public function show(informe $informe)
    {
        return view('informe.index', compact('informe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\informe  $informe
     * @return \Illuminate\Http\Response
     */
    public function edit(informe $informe)
    {
        $docente = Docente::all();
        $categoria = Categoria::all();
        $autor = Autor::all();
        return view('informe.edit', compact('informe','docente', 'categoria', 'autor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\informe  $informe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, informe $informe)
    {
        $request->validate([
            'nombre'=>'required',
            'descripcion'=>'required',
            'codigo'=>'required',
            'fecha'=>'required',
            'centro'=>'required',
            'docente'=>'required',
            'categoria'=>'required',
            'autor'=>'required',
        ]);

        if($request->hasFile('pdf')){
            $request->validate([
                'pdf'=>'required',
            ]);

            // $path = '/storage/imagenes/'.$request->li_image;
            // if(File::exists($path))
            // {
            //     File::delete($path);
            // }
            $url = str_replace('storage','public', $informe->info_pdf);
            // Storage::delete($url);

            $pdf = $request->file('pdf')->store('public/documento');
            $informe->info_pdf = Storage::url($pdf);

            Storage::delete($url);
        }
        //$informe = new informe();

        $informe->info_nombre = $request->nombre;
        $informe->info_descripcion = $request->descripcion;
        $informe->info_codigo = $request->codigo;
        $informe->info_centro = $request->centro;
        $informe->info_fecha = $request->fecha;
        $informe->docente_id = $request->docente;
        $informe->categoria_id = $request->categoria;
        $informe->autor_id = $request->autor;

        $informe->save();

        return redirect()->route('informes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\informe  $informe
     * @return \Illuminate\Http\Response
     */
    public function destroy(informe $informe)
    {
        $informe->delete();

        return back()->with('eliminar', 'delete');
    }
}

resources/views/informe/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Informe')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Crear Informe</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('informes.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6 mt-2">
                                <label>Nombre del Informe</label>
                                <input type="text" class="form-control" id="inputEmail4" name="nombre"
                                    value="{{ old('nombre') }}">
                                @error('nombre')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 mt-2">
                                <label>Codigo del Informe</label>
                                <input type="text" class="form-control" id="inputEmail4" name="codigo"
                                    value="{{ old('codigo') }}">
                                @error('codigo')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 mt-2">
                                <label>Centro de Practicas</label>
                                <input type="text" class="form-control" id="inputEmail4" name="centro"
                                    value="{{ old('centro') }}">
                                @error('centro')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 mt-2">
                                <label>Subir Informe</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="pdf"
                                        value="{{ old('pdf') }}" accept="file/*">
                                    <label class="custom-file-label" for="inputGroupFile01">Seleccione un pdf</label>
                                </div>
                                @error('pdf')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6 mt-2">
                                <label>Fecha del Informe</label>
                                <input type="date" class="form-control" id="inputEmail4" name="fecha"
                                    value="{{ old('fecha') }}">
                                @error('fecha')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                              <label class="mb-3">Categoria</label>
                              <select class="selectpicker form-control" data-style="btn-default" data-size="10" data-live-search="true" name="categoria">
                                <option >Seleccionar...</option>
                                @foreach ($categoria as $item)
                                <option value="{{ $item->id }}">{{ $item->cate_nombre }}</option>
                                @endforeach
                              </select>
                              @error('categoria')
                              <small class="text-danger">{{ $message }}</small>
                              @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="mb-3">Docente</label>
                                <select class="selectpicker form-control" data-style="btn-default" data-size="5" data-live-search="true" name="docente" >
                                  <option >Seleccionar...</option>
                                    @foreach ($docente as $item)
                                        <option value="{{ $item->id }}">{{ $item->doce_nombre }} {{ $item->doce_paterno}} {{ $item->doce_materno }}</option>
                                    @endforeach
                                </select>
                                @error('docente')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="mb-3">Autor</label>
                                <select class="selectpicker form-control dropup" data-dropup-auto="false" data-style="btn-default" data-size="5" data-live-search="true" name="autor">
                                <option >Seleccionar...</option>
                                  @foreach ($autor as $item)
                                        <option value="{{ $item->id }}">{{ $item->au_nombre }} {{ $item->au_paterno }} {{ $item->au_materno }}</option>
                                  @endforeach
                                </select>
                                @error('autor')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                        </div>
                        <div class="form-group">
                            <label>Descripción</label>
                            <textarea class="form-control col-md-12" rows="3" name="descripcion" value="{{ old('descripcion') }}"></textarea>
                            @error('descripcion')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="row justify-content-center">
                            <a href="{{ route('informes.index') }}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
                            <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
                        </div>

                    </form>
                </div>
            </div>
            {{-- 
    <div class="shadow p-5 mb-5 bg-white rounded">
        
    </div> --}}
        </div>
    </div>
@stop

@section('js')

<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
{{-- <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script> --}}

<script>
  $(function () {
    $('select').selectpicker();
});
</script>
@stop

resources/views/informe/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Informe')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Editar Informe</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-6 offset-md-3 mt-5">
<div class="card">
  <div class="card-body">
    <form action="{{route('informes.update', $informe)}}" method="post" enctype="multipart/form-data">
      @csrf
      @method('put')
      <div class="form-row">
        <div class="form-group col-md-6 mt-2">
          <label>Nombre del Informe</label>
          <input type="text" class="form-control" id="inputEmail4" name="nombre" value="{{old('nombre',$informe->info_nombre)}}">
            @error('nombre')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Codigo del Informe</label>
          <input type="text" class="form-control" id="inputEmail4" name="codigo" value="{{old('codigo', $informe->info_codigo)}}">
            @error('codigo')
            <small class="text-danger">{{$message}}</small>
            @enderror
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Centro de Practicas</label>
          <input type="text" class="form-control" id="inputEmail4" name="centro" value="{{old('centro', $informe->info_centro)}}">
            @error('centro')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Subir Informe</label>
          <span class="badge bg-warning"><a href="{{$informe->info_pdf}}" class="m-2 text-white" target="_blank">Ver Informe</a></span>
          <div class="custom-file">
            <input type="file" class="custom-file-input" name="pdf" accept="file/*">
            <label class="custom-file-label" for="inputGroupFile01">Seleccione un pdf</label>
          </div>
          @error('pdf')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Fecha del Informe</label>
          <input type="date" class="form-control" id="inputEmail4" name="fecha" value="{{old('fecha', $informe->info_fecha)}}">
          @error('fecha')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6">
          <label class="mb-3">Categoria</label>
          <select class="selectpicker form-control" data-style="btn-default" data-size="5" data-live-search="true" name="categoria">
            @foreach ($categoria as $item)
            <option value="{{$item->id}}" {{ old('categoria', $informe->categoria_id) == $item->id ? 'selected' : '' }}>{{$item->cate_nombre}}</option>
            @endforeach
          </select>
          <!--<p value=" ">{{$informe->categoria_id}}</p>-->
          @error('categoria')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6">
          <label class="mb-3">Docente</label>
          <select class="selectpicker form-control" data-style="btn-default" data-size="5" data-live-search="true" name="docente">
            @foreach ($docente as $item)
            <option value="{{$item->id}}" {{ old('docente', $informe->docente_id) == $item->id ? 'selected' : '' }}>{{$item->doce_nombre}} {{$item->doce_paterno}} {{$item->doce_materno}}</option>
            @endforeach
          </select>
          @error('docente')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6">
          <label class="mb-3">Autor</label>
          <select class="selectpicker form-control" data-style="btn-default" data-size="5" data-live-search="true" name="autor">
            @foreach ($autor as $item)
            <option value="{{$item->id}}" {{ old('autor', $informe->autor_id) == $item->id ? 'selected' : '' }}>
              {{$item->au_nombre}} {{$item->au_paterno}} {{$item->au_materno}}</option>
            @endforeach
          </select>
          @error('autor')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>

      </div>
        <div class="form-group">
          <label>Descripción</label>
          <textarea class="form-control col-md-12" rows="3" name="descripcion">{{old('descripcion',$informe->info_descripcion)}}</textarea>
              @error('descripcion')
              <small class="text-danger">{{$message}}</small>
              @enderror
      </div>
      <div class="row justify-content-center"> 
        <a href="{{route('informes.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
        <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
      </div>
    </form>
  </div>
</div>
    {{-- <div class="shadow p-5 mb-5 bg-white rounded">
        
    </div> --}}

  </div>
</div>
@stop

@section('js')

<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>

<script>
  $(function () {
    $('select').selectpicker();
});
</script>
@stop 

resources/views/informe/index.blade.php
@extends('adminlte::page')

@section('title', 'Informe')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Lista de Informes</h1>
@stop

@section('content')
<a class="btn btn-info mb-3" href="{{route('informes.create')}}">Crear Nuevo Informe</a>
<div class="card">
  <div class="card-body">
    <div class="table-responsive">    
      <table class="table table table-striped" id="tinforme">
          <thead class="thead-dark">
            <tr>
              <th>Nombre</th>
              <th>Codigo</th>
              <th>Centro</th>
              <th>Docente</th>
              <th>Practicas</th>
              <th>Estudiante</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($informe as $item)
            <tr>
              <td>{{$item->info_nombre}}</td>
              <td>{{$item->info_codigo}}</td>
              <td>{{$item->info_centro}}</td>
              <td>{{$item->docente->doce_nombre}} {{$item->docente->doce_paterno}} {{$item->docente->doce_materno}}</td>
              <td>{{$item->categoria->cate_nombre}}</td>
              <td>{{$item->autor->au_nombre}} {{$item->autor->au_paterno}} {{$item->autor->au_materno}}</td>
              <td width="140px">
                <a href="{{$item->info_pdf}}" class="btn btn-outline-dark btn-sm" target="_blank"><i class="fas fa-lg fa-file"></i></a>
                <a href="{{route('informes.edit', $item)}}" class="btn btn-outline-success btn-sm"><i class="fas fa-lg fa-edit"></i></a>
                <form action="{{route('informes.destroy', $item)}}" method="post" style="display: inline;" class="eliminar"> @csrf @method('delete') <button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-lg fa-trash"></i></button></form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
  </div>
</div>
@stop

@section('js')

@if(session('eliminar') == 'delete')
<script>
 Swal.fire(
          '¡Eliminado!',
          'El registro ha sido eliminado.',
          'success'
        )
</script>
@endif
<script>
  $('.eliminar').submit(function(e){
    e.preventDefault();

    Swal.fire({
      title: '¿Estas seguro?',
      text: "No podrás revertir esto!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: '¡Si, eliminarlo!',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {

        this.submit();
      }
    })

  });

  $('#tinforme').DataTable({
    responsive: true,
    autoWidth: false,
    "language": {
          "lengthMenu": "Mostrar "+`
          <select class="custom-select custom-select-sm form-control form-control-sm">
            <option value="10">10</option> 
            <option value="25">25</option> 
            <option value="50">50</option> 
            <option value="100">100</option> 
            <option value="-1">All</option> 
          </select>
          `+" registros por paginas",
          "zeroRecords": "Nada encontrado - lo siento",
          "info": "Mostrando la pagina _PAGE_ de _PAGES_",
          "infoEmpty": "No records available",
          "infoFiltered": "(filtrado de _MAX_ registro total)",
          "search":"Buscar: ",
          "paginate":{
            "next": "Siguiente",
            "previous": "Anterior"
          }
      }
  });
</script>
@stop