routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\LibroController;
use App\Http\Controllers\CategoriaController;
use App\Http\Controllers\AutorController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\BibliotecaController;
use App\Http\Controllers\BinformeController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolesController;
use Spatie\Permission\Contracts\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/',[BibliotecaController::class, 'index']);

Auth::routes();

//--------------DOCENTE---------------------//

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('docente',[DocenteController::class,'index'])->name('docente.index');

// Route::get('docente/create', [DocenteController::class, 'create'])->name('docente.create');

// Route::get('docente/{docente}', [DocenteController::class, 'show'])->name('curso.show');

// Route::post('docente',[DocenteController::class,'store'])->name('docente.store');

// Route::get('docente/{docente}/edit',[DocenteController::class,'edit'])->name('docente.edit');

// Route::put('docente/{docente}',[DocenteController::class,'update'])->name('docente.update');

// Route::delete('docente/{docente}',[DocenteController::class,'destroy'])->name('docente.destroy');

Route::resource('docentes', DocenteController::class);
//--------------LIBRO---------------------//

// Route::get('libro',[LibroController::class,'index'])->name('libro.index');

// Route::get('libro/create', [LibroController::class, 'create'])->name('libro.create');

// Route::get('libro/{libro}', [LibroController::class, 'show'])->name('libro.show');

// Route::post('libro',[LibroController::class,'store'])->name('libro.store');

// Route::get('libro/{libro}/edit',[LibroController::class,'edit'])->name('libro.edit');

// Route::put('libro/{libro}',[LibroController::class,'update'])->name('libro.update');

// Route::delete('libro/{libro}',[LibroController::class,'destroy'])->name('libro.destroy');


Route::resource('libros', LibroController::class);

Route::get('biblioteca',[BibliotecaController::class, 'index']);


Route::get('/informe', [BinformeController::class, 'index']);


//--------------CATEGORIA---------------------//

// Route::get('categoria',[CategoriaController::class,'index'])->name('categoria.index');

// Route::get('categoria/create',[CategoriaController::class,'create'])->name('categoria.create');

// Route::get('categoria/{show}',[CategoriaController::class,'show'])->name('categoria.show');

// Route::post('categoria',[CategoriaController::class,'store'])->name('categoria.store');

// Route::get('categoria/{categoria}/edit',[CategoriaController::class,'edit'])->name('categoria.edit');

// Route::put('categoria/{categoria}',[CategoriaController::class,'update'])->name('categoria.update');

// Route::delete('categoria/{categoria}',[CategoriaController::class,'destroy'])->name('categoria.destroy');

Route::resource('categorias', CategoriaController::class);

//--------------AUTOR---------------------//

// Route::get('autor',[AutorController::class,'index'])->name('autor.index');

// Route::get('autor/create',[AutorController::class,'create'])->name('autor.create');

// Route::get('autor/{show}',[AutorController::class,'show'])->name('autor.show');

// Route::post('autor',[AutorController::class,'store'])->name('autor.store');

// Route::get('autor/{autor}/edit',[AutorController::class,'edit'])->name('autor.edit');

// Route::put('autor/{autor}',[AutorController::class,'update'])->name('autor.update');

// Route::delete('autor/{autor}',[AutorController::class,'destroy'])->name('autor.destroy');

Route::resource('autors', AutorController::class);

//--------------INFORME---------------------//

// Route::get('informe',[InformeController::class,'index'])->name('informe.index');

// Route::get('informe/create',[InformeController::class,'create'])->name('informe.create');

// Route::get('informe/{show}',[InformeController::class,'show'])->name('informe.show');

// Route::post('informe',[InformeController::class,'store'])->name('informe.store');

// Route::get('informe/{informe}/edit',[InformeController::class,'edit'])->name('informe.edit');

// Route::put('informe/{informe}',[InformeController::class,'update'])->name('informe.update');

// Route::delete('informe/{informe}',[InformeController::class,'destroy'])->name('informe.destroy');

Route::resource('informes', InformeController::class);
// USUARIOS Y ROLES 

Route::resource('usuarios', UsuarioController::class);
Route::resource('roles', RolesController::class);
Route::resource('perfil', PerfilController::class);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/autor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class autor extends Model
{
    use HasFactory;

    //Relacion de uno a muchos
    public function informes(){
        return $this->hasMany(Informe::class);
    }
}

app/Http/Controllers/AutorController.php
<?php

namespace App\Http\Controllers;

use App\Models\autor;
use Illuminate\Http\Request;

class AutorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $autores = Autor::all();
        return view('autor.index', compact('autores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('autor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required',
            'paterno'=>'required',
            'materno'=>'required',
            'codigo'=>'required|numeric',
            'sexo'=>'required',
            'correo'=>'required',
            'celular'=>'required|numeric',
        ]);

        $autores = new Autor();

        $autores->au_nombre = $request->nombre;
        $autores->au_paterno = $request->paterno;
        $autores->au_materno = $request->materno;
        $autores->au_codigo = $request->codigo;
        $autores->au_sexo = $request->sexo;
        $autores->au_correo = $request->correo;
        $autores->au_celular = $request->celular;
        
        $autores->save();
        
        return redirect()->route('autors.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function show(autor $autor)
    {
        return view('autor.index', compact('autor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function edit(autor $autor)
    {
        return view('autor.edit', compact('autor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, autor $autor)
    {
        $request->validate([
            'nombre'=>'required',
            'paterno'=>'required',
            'materno'=>'required',
            'codigo'=>'required|numeric',
            'sexo'=>'required',
            'correo'=>'required',
            'celular'=>'required|numeric',
        ]);

        //$autores = new Autor();

        $autor->au_nombre = $request->nombre;
        $autor->au_paterno = $request->paterno;
        $autor->au_materno = $request->materno;
        $autor->au_codigo = $request->codigo;
        $autor->au_sexo = $request->sexo;
        $autor->au_correo = $request->correo;
        $autor->au_celular = $request->celular;
        
        $autor->save();
        
        return redirect()->route('autors.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\autor  $autor
     * @return \Illuminate\Http\Response
     */
    public function destroy(autor $autor)
    {
        $autor->delete();

        return back()->with('eliminar', 'delete');
    }
}

resources/views/autor/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Estudiante')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Crear Estudiante</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-6 offset-md-3 mt-5">
<div class="card">
  <div class="card-body">
    <form action="{{route('autors.store')}}" method="post">
      @csrf
      <div class="form-row">
        <div class="form-group col-md-6 mt-2">
          <label>Nombre</label>
          <input type="text" class="form-control" id="inputEmail4" name="nombre" value="{{old('nombre')}}">
            @error('nombre')
            <small class="text-danger">{{$message}}</small>
            @enderror 

        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Apellido Paterno</label>
          <input type="text" class="form-control" id="inputEmail4" name="paterno" value="{{old('paterno')}}">

            @error('paterno')
            <small class="text-danger">{{$message}}</small>
            @enderror 

        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Apellido Materno</label>
          <input type="text" class="form-control" id="inputEmail4" name="materno" value="{{old('materno')}}">

            @error('materno')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Codigo de Matricula</label>
          <input type="text" class="form-control" id="inputEmail4" name="codigo" value="{{old('codigo')}}">

            @error('codigo')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6">
          <label class=" mb-3">Genero</label>
          <select id="inputState" class="form-control" name="sexo">
            <option value="">Seleccionar</option>
            <option value="Masculino">Masculino</option>
            <option value="Femenino">Femenino</option>
            <option value="No Especificado">No Especificado</option>
          </select>
          @error('sexo')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Numero de Celular</label>
          <input type="text" class="form-control" id="inputEmail4" name="celular" value="{{old('celular')}}">
          @error('celular')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6 justify-content-center mt-2">
          <label>Correo Electronico</label>
          <input type="text" class="form-control" id="inputEmail4" name="correo" value="{{old('correo')}}">
          @error('correo')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
      </div>
      <div class="row justify-content-center">
        <a href="{{route('autors.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
        <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
      </div>
    </form>
  </div>
</div>
    {{-- 
    <div class="shadow p-5 mb-5 bg-white rounded">
        
    </div>
     --}}

  </div>
</div>

@stop

resources/views/autor/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Estudiante')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Editar Estudiante</h1>
@stop

@section('content')
<div class="row">
  <div class="col-md-6 offset-md-3 mt-5">
<div class="card">
  <div class="card-body">
    <form action="{{route('autors.update', $autor)}}" method="post">
      @csrf
      @method('put')
      <div class="form-row">
        <div class="form-group col-md-6 mt-2">
          <label>Nombre</label>
          <input type="text" class="form-control" id="inputEmail4" name="nombre" value="{{old('nombre',$autor->au_nombre)}}">
            @error('nombre')
            <small class="text-danger">{{$message}}</small>
            @enderror 

        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Apellido Paterno</label>
          <input type="text" class="form-control" id="inputEmail4" name="paterno" value="{{old('paterno', $autor->au_paterno)}}">

            @error('paterno')
            <small class="text-danger">{{$message}}</small>
            @enderror 

        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Apellido Materno</label>
          <input type="text" class="form-control" id="inputEmail4" name="materno" value="{{old('materno', $autor->au_materno)}}">
            @error('materno')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Codigo de Matricula</label>
          <input type="text" class="form-control" id="inputEmail4" name="codigo" value="{{old('codigo', $autor->au_codigo)}}">
            @error('codigo')
            <small class="text-danger">{{$message}}</small>
            @enderror 
        </div>
        <div class="form-group col-md-6">
          <label class=" mb-3">Genero</label>
          <select class="form-control" name="sexo">
              <option value="Masculino"  {{ old('genero', $autor->au_sexo) == 'Masculino' ? 'selected' : '' }}>Masculino</option>
              <option value="Femenino" {{ old('genero', $autor->au_sexo) == 'Femenino' ? 'selected' : '' }}>Femenino</option>
              <option value="No especificado" {{ old('genero', $autor->au_sexo) == 'No Especificado' ? 'selected' : '' }}>No Especificado</option>
          </select>
          @error('sexo')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6 mt-2">
          <label>Numero de Celular</label>
          <input type="text" class="form-control" id="inputEmail4" name="celular" value="{{old('celular', $autor->au_celular)}}">
          @error('celular')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
        <div class="form-group col-md-6 justify-content-center mt-2">
          <label>Correo Electronico</label>
          <input type="text" class="form-control" id="inputEmail4" name="correo" value="{{old('correo', $autor->au_correo)}}">
          @error('correo')
          <small class="text-danger">{{$message}}</small>
          @enderror 
        </div>
      </div>
      <div class="row justify-content-center">
        <a href="{{route('autors.index')}}" class="btn btn-info m-3 col-md-3 p-1">Regresar</a>
        <button type="submit" class="btn btn-success m-3 col-md-3">Enviar</button>
      </div>
    </form>
  </div>
</div>
    {{-- <a href="{{route('autor.store')}}" class="btn btn-info mb-3">Regresar Lista Estudiantes</a>
    <div class="shadow p-5 mb-5 bg-white rounded">
       
    </div> --}}
  </div>
</div>
@stop

resources/views/autor/index.blade.php
@extends('adminlte::page')

@section('title', 'Autor')

@section('content_header')
    <h1 class="text-center font-weight-bold text-uppercase">Lista de Estudiantes</h1>
@stop

@section('content')

<a class="btn btn-info mb-3" href="{{route('autors.create')}}">Crear Nuevo Estudiante</a>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">    
            <table class="table table-striped text-center" id="tautor">
                <thead class="thead-dark">
                    <tr>
                    <th>Nombre</th>
                    <th>Paterno</th>
                    <th>Materno</th>
                    <th>Codigo</th>
                    <th>Sexo</th>
                    <th>Correo</th>
                    <th>Celular</th>
                    <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($autores as $item)
                    <tr>
                    <td>{{$item->au_nombre}}</td>
                    <td>{{$item->au_paterno}}</td>
                    <td>{{$item->au_materno}}</td>
                    <td>{{$item->au_codigo}}</td>
                    <td>{{$item->au_sexo}}</td>
                    <td>{{$item->au_correo}}</td>
                    <td>{{$item->au_celular}}</td>
                    <td width="140px">
                        <a href="{{route('autors.edit', $item)}}" class="btn btn-outline-success btn-sm"><i class="fas fa-lg fa-edit"></i></a>
                        <form action="{{route('autors.destroy', $item)}}" method="post" style="display: inline" class="eliminar"> @csrf @method('delete') <button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-lg fa-trash"></i></button></form>
                    </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@stop

@section('js')

@section('js')
@if(session('eliminar') == 'delete')
<script>
 Swal.fire(
          '¡Eliminado!',
          'El registro ha sido eliminado.',
          'success'
        )
</script>
@endif
<script>
  $('.eliminar').submit(function(e){
    e.preventDefault();

    Swal.fire({
      title: '¿Estas seguro?',
      text: "No podrás revertir esto!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: '¡Si, eliminarlo!',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {

        this.submit();
      }
    })

  });
</script>

<script>
    $('#tautor').DataTable({
        responsive: true,
        autoWidth: false,
        "language": {
            "lengthMenu": "Mostrar "+`
            <select class="custom-select custom-select-sm form-control form-control-sm">
                <option value="10">10</option> 
                <option value="25">25</option> 
                <option value="50">50</option> 
                <option value="100">100</option> 
                <option value="-1">All</option> 
            </select>
            `+" registros por paginas",
            "zeroRecords": "Nada encontrado - lo siento",
            "info": "Mostrando la pagina _PAGE_ de _PAGES_",
            "infoEmpty": "No records available",
            "infoFiltered": "(filtrado de _MAX_ registro total)",
            "search":"Buscar: ",
            "paginate":{
                "next": "Siguiente",
                "previous": "Anterior"
            }
        }
    });
</script>
@stop